# Loop Invariants


In [ ]:
"""
Compute the n'th number in the fibonacci sequence 
a(n) = a(n-1) + a(n-2) given a(0) and a(1)

Assumes n ≥ 2
"""
function fibonacci(a0, a1, n)
    # assumptions (check if you want)
    
    # initialization
    k = 1
    aₙ = a1
    aₙ₋₁ = a0
    
    #=
        loop invariant:
        - aₙ is the k'th number in the sequence
        - aₙ₋₁ is the k-1'th number in the sequence
    =#
    while k ≠ n # termination condition
        # progress
        k += 1
        # fix loop invariant
        aₙ₊₁ = aₙ + aₙ₋₁
        aₙ₋₁ = aₙ
        aₙ = aₙ₊₁
    end
    
    return aₙ
end

## Ternary operator

In [25]:
false ? "hi" : "bye"

"bye"

# Arrays and Comprehension

- operations on arrays 
- element-wise operations on arrays
- list/vector comprehension
- array comprehension

In [31]:
A = [1 2; 3 4]
B = [1 1; 3 3]
f(x) = mod(x,2) == 0 ? 3 : 10
f.(A)

2×2 Matrix{Int64}:
 10  3
 10  3

In [33]:
vector = [ [2 * i * j for i in 1:12] for j in 1:3]

3-element Vector{Vector{Int64}}:
 [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
 [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48]
 [6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72]

In [37]:
A = [ i * j for i in 1:4, j in 1:5]

4×5 Matrix{Int64}:
 1  2   3   4   5
 2  4   6   8  10
 3  6   9  12  15
 4  8  12  16  20

### Exercises

1) Write a function that takes in a number `n` and another number `d` and returns a length `n` vector with 1's in every position that is a multiple of `d`
2) Write a function that takes in two numbers `n` and `m` and returns an `n`-by-`m` matrix that has 1's in every position where the sum of the indices is even. For example, a 2-by-3 matrix should look like the following. $$\begin{bmatrix}1 & 0 & 1 \\ 0 & 1 & 0 \end{bmatrix} $$
3) Suppose we want to find the best polynomial $p(x) = a_0+a_1x+\ldots +a_nx^n$ that approximates a function $f$, where the approximation is exact at $n+1$ distinct points, i.e. $p(x)=f(x)$ at the points $(x_0, f(x_0)),\ldots, (x_n, f(x_n))$. Write a function that takes in two length `n` vectors, one of $x$-values, and the other with the corresponding $f(x)$-values, and outputs the vector of coefficients of the approximating polynomial.
4) For problem (3), instead of outputting the coefficients of the approximating polynomial, output a function $p$ that has one input $x$ and returns the value of the approximating polynomial a that point $x$.
5) For problem (3), instead of having as input the vector of $x$-values and $f$-values, use as input a function $f$, two endpoints of an interval $[a,b]$, and the degree $n$ of the approximating polynomial.

In [40]:
function ones_every_d(n, d)
    x = zeros(n)
    for i in 1:n
        if mod(i, d) == 0
            x[i] = 1
        end
    end
    return x
end

function ones_every_d_v2(n,d)
    return [mod(i,d) == 0 ? 1 : 0 for i in 1:n]
end

ones_every_d_v2 (generic function with 1 method)

In [41]:
ones_every_d_v2(10,3)

10-element Vector{Int64}:
 0
 0
 1
 0
 0
 1
 0
 0
 1
 0

In [43]:
function eval_f(f, x)
    return f(x)
end


eval_f (generic function with 1 method)

In [44]:
eval_f(cos, 1)

0.5403023058681398

In [45]:
typeof(cos)

typeof(cos) (singleton type of function cos, subtype of Function)